### ISSUE TITLE
Como faz pra ajudar?

### ISSUE THREAD

**Issue by DouglasHennrich** [willianjusten/reveal-boilerplate#3]
Gostei muito desse negócio de slides pelo gh-pages e revealjs... gostaria de saber como eu faço para te dar uma mão... vale lembrar que não acostumado com nada do que tem aqui, mas é uma boa maneira de aprender =)

**Comment by willianjusten** [comment]
Então cara, o Reveal tem vários [temas](https://github.com/hakimel/reveal.js/tree/master/css/theme), se você quiser portá-los para Stylus e dar a permissão da pessoa escolher os diferentes temas só modificando no `main.styl`já seria uma ótima adição!

**Comment by willianjusten** [comment]
Existe um conversor web que passa de css para stylus e facilita bastante, que é o [css2stylus](http://css2stylus.com/). Mas como você disse que é novato, dá uma lida na documentação do [Stylus](https://learnboost.github.io/stylus/) para você ir conhecendo e entendendo, é uma ótima forma de estudar =)

**Comment by DouglasHennrich** [comment]
blz! Eu notei mesmo que só tinha aquele tema "branco", vou ver se consigo colocar mais temas =)

**Comment by DouglasHennrich** [comment]
Ta meio complicado de entender como funciona X_X
foda que nunca fui programador web huaheuhaeuhae
sabe como eu faço pra importar aquelas fontes?
eu tentei:
`@import url(https://fonts.googleapis.com/css?family=Ubuntu:300,700,300italic,700italic)`
mas parece que não importou essa fonte =/
outra coisa... eu notei que no seu `white.styl` tem algo parecido com isso:
```css
.reveal
  font-family Helvetica, sans-serif
  font-size 38px
  font-weight normal
  color #222
  h1
    font-size 2.5em
    text-shadow none
  h2
    font-size 1.6em
```

e logo mais em baixo:

```css
.reveal h1, .reveal h2, .reveal h3, .reveal h4, .reveal h5, .reveal h6
  margin 0 0 20px 0
  color #222
  font-family Helvetica, sans-serif
  font-weight 600
  ...
```

Não entendi pq tem 2x esses `h1``h2``h3`... sendo que vc já colocou eles dentro do primeiro `.reveal`... seria pra não ter que add em cada um toda aquela tripa que segue? ou eles são diferentes?

Valeu e desculpa pelas perguntas amadoras =X

**Comment by DouglasHennrich** [comment]
esquece a ultima parte da minha pergunta... seria mesmo só como importar as fontes que eles usam... fiz um pull request com o blood theme... ve se é assim que se faz xD
outra coisa.. não faço ideia de como a gente pode fazer pra escolher qual tema usar, visto que o main importa todos os themes e ta jogando no `head`

**Comment by willianjusten** [comment]
Vou dar uma olhada mais tarde, estou no trabalho e aí fica difícil de ver.

**Comment by DouglasHennrich** [comment]
Tranquilo!
Eu notei que só passando os CSS dos Themes, o stylus já reconhece eles e funciona tranquilo, sem precisar passar pro stylus

**Comment by willianjusten** [comment]
E sobre como chamar, basta que o cara dentro do `main.styl` defina qual tema usar.

**Comment by DouglasHennrich** [comment]
entao ta tranquilo... vou deixar comentado os temas que tem e deixar um default e deixar que ele escolha qual tema "descomentar" e usar

Quanto a importar as fontes, sabe como fazer?
Sem pressa ^^
Abraço

**Comment by willianjusten** [comment]
É bem simples, mas se liga, cria uma pasta `themes` para ficar mais organizado...

**Comment by willianjusten** [comment]
Eu organizei um pouco as coisas aqui, depois vou melhorar a documentação e explicar como fazer o port dos themes, por enquanto estarei fechando essa issue aqui também, pois irei criar uma com as explicações.
